name: cims
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  android_id: ^0.3.5
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.3
  device_info: ^2.0.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  liquid_pull_to_refresh: ^3.0.1
  scroll_snap_list: ^0.9.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.12
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.2.2
  provider: ^6.0.5
  flutter_pdfview: ^1.3.1
  syncfusion_flutter_pdfviewer: ^22.2.10
  flutter_local_notifications: ^15.1.1
  flutter_app_badger: ^1.5.0
  image_picker: ^1.0.4
  tuple: ^2.0.2
  lottie: ^2.6.0
  path_provider: ^2.1.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 

  flutter_native_splash: ^2.0.1+1
  
flutter_native_splash:
  color: "#000000"
  image: assets/images/login.png
flutter:
  uses-material-design: true
  assets:
    - assets/images/ccmt1.png
    - assets/images/login.png
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/background.png
    - assets/images/pou.png
    - assets/images/linkedin.png
    - assets/images/insta.jpeg
    - assets/images/facebook.png